steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/rp-app-355907/research_project_app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/rp-app-355907/research_project_app']
